import sharp from "sharp";
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const output = path.join(root, "public/optimized");
await mkdir(output, { recursive: true });
const manifest = {};
const backgroundRules = [[], [], []];
let sourceBytes = 0;
let largestBytes = 0;
for (const directory of ["products", "bg", "team-logos"]) {
  for (const file of (await readdir(path.join(root, "public", directory))).sort()) {
    if (!/\.(png|jpe?g|webp)$/i.test(file)) continue;
    const input = await readFile(path.join(root, "public", directory, file));
    const metadata = await sharp(input).metadata();
    const widths = [...new Set([320, 640, 960, 1440, 1920].map((width) => Math.min(width, metadata.width)))];
    const hash = createHash("sha256").update(input).update(`webp82-v1-${sharp.versions.sharp}-${sharp.versions.vips}`).digest("hex").slice(0, 12);
    const stem = `${directory}-${path.parse(file).name}`.replace(/[^a-zA-Z0-9-]/g, "-");
    const variants = [];
    for (const width of widths) {
      const name = `${stem}-${hash}-${width}.webp`;
      let data;
      try { data = await readFile(path.join(output, name)); }
      catch {
        data = await sharp(input).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: 82, effort: 5 }).toBuffer();
        await writeFile(path.join(output, name), data);
      }
      variants.push({ src: `/optimized/${name}`, width });
      if (width === widths.at(-1)) largestBytes += data.length;
    }
    sourceBytes += input.length;
    manifest[`/${directory}/${file}`] = { width: metadata.width, height: metadata.height, variants };
    if (directory === "bg") {
      const variable = `--image-${path.parse(file).name.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase()}`;
      [960, 1440, 1920].forEach((size, index) => {
        const variant = variants.find((entry) => entry.width >= size) || variants.at(-1);
        backgroundRules[index].push(`  ${variable}: url("${variant.src}");`);
      });
    }
  }
}
await writeFile(path.join(root, "src/image-manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
await writeFile(path.join(root, "src/css/responsive-images.css"), `/* Generated by npm run images; edit the source images or generator. */\n:root {\n${backgroundRules[2].join("\n")}\n}\n@media (max-width: 1100px) {\n  :root {\n${backgroundRules[1].join("\n")}\n  }\n}\n@media (max-width: 700px) {\n  :root {\n${backgroundRules[0].join("\n")}\n  }\n}\n`);
const heroes = Object.fromEntries(Object.entries({
  "/": "/bg/colnago.webp",
  "/gear": "/products/bike_cervelo.png",
  "/support": "/bg/cervelo-support.jpg",
  "/account": "/bg/cervelo-support.jpg",
}).map(([route, source]) => [route, { ...manifest[source], background: source.startsWith("/bg/") }]));
await writeFile(path.join(root, "src/hero-images.json"), JSON.stringify(heroes, null, 2) + "\n");
console.log(`Generated ${Object.keys(manifest).length} responsive images. Largest variants: ${(largestBytes / 1048576).toFixed(2)} MB; originals: ${(sourceBytes / 1048576).toFixed(2)} MB.`);
